#config.yaml: a file that is used to coordinate the training data
# Path has been abbreivated for privacy concerns
path: \AI_Mini_Proj\Data #dataset root dir

train: images/train
val: images/val

# Classes
names: 
  0: ARM_RIGHT
  1: ARM_LEFT
